from typing import Sequence
import numpy as np

class YoungLaplaceShape:
    def __init__(self, bond: float) -> None: ...

    def __call__(self, s: float) -> np.ndarray: ...

    def DBo(self, s: float) -> np.ndarray: ...

    def z_inv(self, s: float) -> float: ...

    def closest(self, r: Sequence[float], z: Sequence[float]) -> np.ndarray: ...

    def volume(self, s: float) -> float: ...

    def surface_area(self, s: float) -> float: ...

    @property
    def bond(self) -> float: ...
    @bond.setter
    def bond(self, value: float) -> None: ...

