repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        exclude: ^dependencies/|setup\.py$|install\.py$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(md|json|yaml|yml|css|js|ts|html)$
        exclude: ^dependencies/
