repos:
    - repo: local
      hooks:
          - id: run-tests
            name: Run test_all.py before push
            entry: python test_all.py
            language: system
            stages: [push]
