# Note: For empty value (`None` in Python), set a value to `null` or leaving it empty.

# --- Image capture settings ---
drop_ID_method: Automated # Method for drop identification for both CA and IFT (Automated or User-selected)
threshold_method: Automated # Method for image thresholding for CA analysis (Automated or User-selected)
needle_region_method: Automated # Method for locating the needle region for IFT analysis (Automated or User-selected)
threshold_val: null # Custom threshold number value (if not automated)
baseline_method: Automated # Method for detecting the baseline for CA analysis (Automated or User-selected)
edgefinder: OpenCV # Edge detection algorithm (OpenCV, Subpixel or Both)

# --- Physical properties input by user (used in IFT analysis) ---
drop_density: 1000 # Density of drop fluid (g/cm³)
density_outer: 0 # Density of surrounding fluid (g/cm³)
needle_diameter_mm: 0.7176 # Diameter of the needle in mm
pixel_mm: null # Calibration factor: mm per pixel

# --- Processing control flags ---
original_boole: 0 # To show original image during analysing (1 for true and 0 for false)
cropped_boole: 0 # To show cropped image during analysing (1 for true and 0 for false)
threshold_boole: 0 # To show threshold image during analysing (1 for true and 0 for false)
image_source: Local images # Source of images (only have Local images option for now)

# --- Image acquisition ---
import_files: null # Optional import file list
frame_interval: 1 # Time between frames/images (float number)

# --- Analysis methods ---
analysis_methods_ca: # Contact angle fitting methods
  TANGENT_FIT: true
  POLYNOMIAL_FIT: true
  CIRCLE_FIT: false
  ELLIPSE_FIT: false
  YL_FIT: false
  ML_MODEL: false
analysis_methods_pd: # IFT fitting methods
  INTERFACIAL_TENSION: true

# --- Output ---
save_images_boole: false # Save image outputs
create_folder_boole: false # Create folder for output files
filename: null # Output filename prefix
output_directory: ./outputs/ # Save directory
